// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql"
	"time"
)

type Url struct {
	ID          int64        `json:"id"`
	ShortCode   string       `json:"short_code"`
	OriginalUrl string       `json:"original_url"`
	CreatedAt   time.Time    `json:"created_at"`
	ExpiresAt   sql.NullTime `json:"expires_at"`
}
