// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: urls.sql

package db

import (
	"context"
)

const createURL = `-- name: CreateURL :one
INSERT INTO urls (
    short_code,
    original_url
) VALUES (
    $1, $2
) RETURNING id, short_code, original_url, created_at, expires_at
`

type CreateURLParams struct {
	ShortCode   string `json:"short_code"`
	OriginalUrl string `json:"original_url"`
}

func (q *Queries) CreateURL(ctx context.Context, arg CreateURLParams) (Url, error) {
	row := q.db.QueryRow(ctx, createURL, arg.ShortCode, arg.OriginalUrl)
	var i Url
	err := row.Scan(
		&i.ID,
		&i.ShortCode,
		&i.OriginalUrl,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const deleteURL = `-- name: DeleteURL :exec
DELETE FROM urls
WHERE short_code = $1
`

func (q *Queries) DeleteURL(ctx context.Context, shortCode string) error {
	_, err := q.db.Exec(ctx, deleteURL, shortCode)
	return err
}

const getURLByShortCode = `-- name: GetURLByShortCode :one
SELECT id, short_code, original_url, created_at, expires_at
FROM urls
WHERE short_code = $1
`

func (q *Queries) GetURLByShortCode(ctx context.Context, shortCode string) (Url, error) {
	row := q.db.QueryRow(ctx, getURLByShortCode, shortCode)
	var i Url
	err := row.Scan(
		&i.ID,
		&i.ShortCode,
		&i.OriginalUrl,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}
